namespace: namespace-teste

app:
  name: app-teste

image:
  repository: raynemarquez/nginx-app
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  path: /
